### ISSUE TITLE
npm 2 + package inconsistency

### ISSUE THREAD

**Issue by kellyselden** [tomdale/broccoli-module-alchemist-install#1]
Scenario: Your express app using fastboot has a lodash dependency. fastboot also depends on najax which also depends on lodash. When running npm install the first time, I get:

```
> DEBUG=broccoli-module-alchemist-install broccoli-module-alchemist-install

Verifying compatibility of src/index.js
Exception caught while evaluating src/index.js
  broccoli-module-alchemist-install Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/my-app/node_modules/fastboot/node_modules/najax/lib/najax.js:12:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17) +0ms
Verifying compatibility of dist/cjs/index.js
Requiring /my-app/node_modules/fastboot/dist/cjs/index.js
  broccoli-module-alchemist-install Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/my-app/node_modules/fastboot/node_modules/najax/lib/najax.js:12:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17) +13ms
Could not load src/index.js or dist/cjs/index.js
```

Later in the log there is a

```
lodash@4.16.6 node_modules/lodash
```

Now, if I delete the "node_modules/fastboot" folder and npm install again, I get:

```
> DEBUG=broccoli-module-alchemist-install broccoli-module-alchemist-install

Verifying compatibility of src/index.js
Exception caught while evaluating src/index.js
  broccoli-module-alchemist-install SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/my-app/node_modules/fastboot/src/ember-app.js:12:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10) +0ms
Verifying compatibility of dist/cjs/index.js
Requiring /my-app/node_modules/fastboot/dist/cjs/index.js
Switching package main to dist/cjs/index.js
```

So it appears npm delayed the install of lodash because it was also used by your consuming application. npm 3 doesn't have the issue.

**Comment by kellyselden** [comment]
FYI the workaround was to add

```
    "postinstall": "rimraf node_modules/fastboot && npm install fastboot"
```

to the package.json
